# Learning Objectives
+ Implementing dynamic programming solutions
+ Learn more complex applications of dynamic programming
+ Implement efficient solutions to various problems in combinatorial optimization.

# Knapsack

## Problem overview

+ Select a set of TV commercials {duration & cost}. The total revenue is maximal while the total length does not exceed the length of the available time slot.

+ Output: the maximal performance under limited budget.

+ Knapsack problem

![knapsack_problem](./figures/knapsack_problem.PNG)

+ Problem variations:
    - Fractional knapsack (take fractions of items)
    - Knapsack
    - Discrete knapsack (each item is either taken or not):
      - With repetitions: unlimited quantities.
      - Without repetitions: one of each item.

+ Example: 
    - We have 4 items: 
      - A {6 parts, total cost: 30}
      - B {3 parts, total cost: 14}
      - C {4 parts, total cost: 16}
      - D {2 parts, total cost: 9}
    - We just pick 10 parts. How to optimal total cost ?

![knapsack_example](./figures/knapsack_example.PNG)

+ Why does greedy fail for the discrete ?
    - Taking an element of maximum value per unit of weight is not safe !

## Knapsack with repetitions

+ Compare knapsack with repetitions & without repetitions:

![compare_with_and_without_repetitions](./figures/compare_with_and_without_repetitions.PNG)

### Knapsack with repetitions problem:
+ Input:
    - *n* items:
      - Weights: $w_1, ..., w_n$
      - Values: $v_1, ..., v_n$
    - Total weight: *W*
+ Output:
    - the maximum value of items whose weight does not exceed W.
    - Each item can be used any number of times.

### Subproblems

- Consider an optimal solution & an item in it.
- If we take this item out then get an *optimal* solution for a knapsack of total weight $W - w_{i}$.

+ Let *value(w)* be the maximum value of knapsack of weight *w*.
    $value(w) = max_{i: w_{i} \leq w} {value(w - w_{i} + v_{i})}$

![knapsack_repetitions](./figures/knapsack_repetitions.PNG)

In [30]:
def knapsack_repetitions(W):
    # dict_items = {
        
    # }
    n = 4
    values = [30, 14, 16, 9]
    weights = [6, 3, 4, 2]
    #
    value = [0] * (W)
    for w in range(W):
        value[w] = 0
        for i in range(n):
            if weights[i] <= w:
                val = value[w - weights[i]] + values[i]
                if val > value[w]:
                    value[w] = val
    return value                    

In [31]:
val = knapsack_repetitions(10)
print(val)

[0, 0, 9, 14, 18, 23, 30, 32, 39, 44]


## Knapsack without repetitions

+ Input: 
    - weights: $w_{1}, ..., w_{n}$
    - values: $v_{1}, ..., v_{n}$
    - Total weights: W
+ Output:
    - the maximum value of items whose weight does not exceed W.
    - Condition: each item can be used at most once.

### Subproblems

+ If the $n^{th}$ item is taken into an optimal solution then what is left is an optimal solution for a knapsack of total weight $W - w_{n}$ using items 1, 2, ..., n - 1.
+ If the $n^{th}$ item is not used then the whole knapsack must be filled in optimally with items 1, 2, ..., n - 1

+ For $0 \leq w \leq W$ and $0 \leq i \leq n$, value(w, i) is the maximum value achievable using a knapsack of weight w and items 1, ..., i
+ The $i^{th}$ item is either used or not

    $value(w, i) = max(value(w - w_{i}, i - 1) + v_{i}, value(w, i - 1))$

+ Pseudo code:

![knapsack_without_repetitions](./figures/knapsack_without_repetitions.PNG)

! Notes:
    - Manage to express the solution for problems through solution for smaller sub-problems.

![knapsack_no_repetitions_example](./figures/knapsack_no_repetitions_example.PNG)

In [53]:
import numpy as np
def knapsack_norepetitions(W):
    weights = [6, 3, 4, 2]
    cost = [30, 14, 16, 9]
    #
    values = np.zeros((len(weights) + 1, W + 1))
    print(values)
    for i in range(1, len(weights) + 1):       # so loai goi hang
        for w in range(1, W + 1):              # so luong goi hang
#             print(i, w)
            values[i][w] = values[i - 1][w] # gia tri voi i-goi hang 
            if weights[i - 1] <= w:
                i = i - 1
                val = values[i - 1][w - weights[i]] + cost[i]
                if values[i][w] < val:
                    values[i][w] = val
    return values[len(weights)][W]     


In [54]:
knapsack_norepetitions(10)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


0.0

## Final remarks

+ Knapsack pseudo code:

![knapsack_pseudo_code](./figures/knapsack_pseudo_code.PNG)

+ First trick - **memoization**, when designing a dynamic program & algorithms:
    - $1^{st}$: analyzing the structure of an optimal solution for computational problem.
    - $2^{nd}$: definition of a sub-problem that will allow you to express the solutions for sub-problem through solutions of smaller sub-problems.
    - $3^{th}$: write down this recurrence relation you can transform it to an ISA alternative algorithm or recursive algorithm.

### What is faster ? 
+ If all sub-problems must be solved then an iterative algorithm is usually faster since it has no recursion overhead.
    - recursive algorithm: solve the same problems
+ There are cases however when one does not need to solve all sub-problems.

### Running time
+ The running time O(nW)
+ *notes*: in other words, the running time is $O(n 2 ^{(log W)})$

# Placing parentheses

 ## Problem overview

+ How to place parentheses in an expression f = 1 + 2 - 3 x 4 - 5, to maximize its value ?
+ Example: 
    - ((((1 + 2)) - 3) x 4) - 5 = - 5
    - ((1 + 2) - ((3 x 4) - 5)) = -4

## Sub-problems

+ Input: a sequence of digits $d_{1}, d_{2}, ..., d_{n}$ & a sequence of operations $op_{1}, ..., op_{n - 1}$ in {+, -, x} 
+ Output: An order of applying these operations that max the value of expression.

   -  $d_{1} op_{1} d_{2} op_{2} ... op_{n - 1} d_{n}$

## Algorithms

## Reconstructing a Solution

# 