# Content


# [2.1 Understanding Data Types in Python](#2.1-Understanding-Data-Types-in-Python)

# [2.2 The Basics of Numpy Arrays](2.2-The-Basics-of-Numpy-Arrays)

# [2.3 Computation on Numpy Arrays: Unversal Functions](2.3-Computation-on-Numpy-Arrays:-Unversal-Functions)


# 2.1 Understanding Data Types in Python

## A python integer is more than just an Integer

+ Mọi object trong python được viết lại (cải trang) bởi cấu trúc C bao gồm giá trị & các thông tin khác.
    - Ex: x=10 ~ bản chất là 1 con trỏ tới 1 khối (hợp chất) cấu trúc C.
    ```
    struct _longobject{
        long ob_refcnt; # a reference count (số tham chiếu), giúp Python handle sự phân bố trong memory.
        PyTypeObject *ob_type; # mã hóa kiểu dữ liệu của biến.
        size_t ob_size; specifies (chỉ định) kích thước của đối tượng dữ liệu 
        long ob_digit[1]; # bao gồm giá trị thực của integer.
    }
    ```
    
    - Minh họa lưu trữ biến integer trong C & Python
    ![Sư khác nhau C & Python integers](./figures/difference_c_python_integer.PNG)
    
        - Với C, số int là 1 nhãn cho 1 vị trí trong bộ nhớ của các bytes mã hóa 1 giá trị int.
        - Với Python, số int là 1 con trỏ tới 1 vị trí trong bộ nhớ chứa toàn bộ thông tin của object bao gồm các bytes chứa giá trị int.

## A Python List is more than just a list

+ List: định dạng có thể thay đổi nhiều thành phần

In [1]:
list_1 = list(range(10))
list_1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
print("Type of list_1: ", type(list_1))
print("Type of element in list_1: ", type(list_1[0]))

Type of list_1:  <class 'list'>
Type of element in list_1:  <class 'int'>


+ Có thể tạo list không đồng nhất (heterogeneous) kiểu dữ liệu:

In [4]:
list_2 = [True, 1, "All"]

+ Python object: bao gồm 
    - Thông tin kiểu dữ liệu 
    - Reference count (số tham chiếu)
    - Các thông tin khác (kích thước được chỉ định cho object, the actual object value)

+ Notes: 
    - list có khả năng linh động kiểu dữ liệu có thể dẫn đến dư thừa tài nguyên. 
    - list chứa 1 con trỏ chỉ tới 1 khối các con trỏ. Mỗi một con trỏ lại chỉ đến 1 đối tượng đầy đủ. 
    - Ưu điểm list là tính linh động nhưng cần cân nhắc việc cố định kiểu (dữ liệu) trong việc xử lý & lưu trữ dữ liệu.
    
+ Sự khác nhau giữa C & Python list
![difference_c_python_list](./figures/difference_c_python_list.PNG)

## Fixed-type Arrays in Python

+ Python có 1 vài lựa chọn cho việc lưu trữ dữ liệu hiêu quả, cố định kiểu dữ liệu bộ đệm.


In [5]:
import array

In [7]:
# Tạo 1 array đồng dạng
list_3 = list(range(5))
a = array.array('i', list_3)
#
a

array('i', [0, 1, 2, 3, 4])

In [8]:
import numpy as np

## Creating Arrays from Python Lists

+ **Notes**: Numpy có hạn chế là các thành phần trong 1 array phải cùng kiểu dữ liệu.

In [9]:
# int array
i_arr = np.array([1, 2, 3, 4])
i_arr

array([1, 2, 3, 4])

In [12]:
i_f_arr = np.array([3.14, 1, 2, 3])
for element in i_f_arr:
    print(type(element))
#
i_f_arr

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


array([3.14, 1.  , 2.  , 3.  ])

+ Sử dụng *dtype* để config kiểu dữ liệu cho array.

In [16]:
f_32_arr = np.array([1, 2, 3, 4], dtype='float32')
f_32_arr

array([1., 2., 3., 4.], dtype=float32)

+ Numpy array có thể tạo nhiều chiều

In [19]:
numb_dimen = 3
m_d_arr = np.array([range(i, i + numb_dimen) for i in [1, 2, 3]])
#
m_d_arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

## Create Arrays from Scratch


In [21]:
num_element = 10
zero_arr = np.zeros(num_element, dtype=int)
#
zero_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
shape_size = (3, 5)
one_arr = np.ones(shape=shape_size,
                  dtype=float)
one_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
shape_size_full = (2, 3)
full_arr = np.full(shape=shape_size_full, 
                  fill_value=3.14)
full_arr

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

+ np.arrange(start, end, step)  # theo thu tu
+ np.linspace(start, end, number_elements) # cach deu

In [29]:
arange_arr = np.arange(1, 10, 1)
arange_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
linspace_arr = np.linspace(0, 2, 10)
linspace_arr

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

+ Tao ngau nhien ma tran phan bo đồng nhất (uniformly)
```
np.random.random((shape))
```

In [33]:
uniform_arr = np.random.random(shape_size)
uniform_arr

array([[0.45978783, 0.90918836, 0.5436754 , 0.25812603, 0.54483946],
       [0.54702174, 0.35936847, 0.21008134, 0.9698777 , 0.73351898],
       [0.82201812, 0.64897638, 0.70389485, 0.03169595, 0.77163756]])

+ Tao ngau nhien ma tran, gia tri trong khoang [a, b] voi kich thuoc (m, n)
```
np.random.randint(a, b, (m, n))
```

In [34]:
rand_arr = np.random.randint(1, 10, (4, 5))
rand_arr

array([[5, 9, 7, 6, 4],
       [6, 7, 1, 9, 4],
       [3, 1, 9, 9, 9],
       [5, 4, 2, 8, 5]])

## Numpy Standard Data Types

# 2.2 The Basics of Numpy Arrays

# 2.3 Computation on Numpy Arrays: Unversal Functions

# 2.4 Aggregation: Min, Max & Everything in Between

# 2.5 Computation on Arrays: Broadcasting

# 2.6 Comparisons, Masks & Boolean Logic

# 2.7 Fancy Indexing

# 2.8 Sorting Arrays

# 2.9 Structured Data: NumPy's Structured Arrays