# Content


# [2.1 Understanding Data Types in Python](#2.1-Understanding-Data-Types-in-Python)

# [2.2 The Basics of Numpy Arrays](2.2-The-Basics-of-Numpy-Arrays)

# [2.3 Computation on Numpy Arrays: Unversal Functions](2.3-Computation-on-Numpy-Arrays:-Unversal-Functions)


# 2.1 Understanding Data Types in Python

## A python integer is more than just an Integer

+ Mọi object trong python được viết lại (cải trang) bởi cấu trúc C bao gồm giá trị & các thông tin khác.
    - Ex: x=10 ~ bản chất là 1 con trỏ tới 1 khối (hợp chất) cấu trúc C.
    ```
    struct _longobject{
        long ob_refcnt; # a reference count (số tham chiếu), giúp Python handle sự phân bố trong memory.
        PyTypeObject *ob_type; # mã hóa kiểu dữ liệu của biến.
        size_t ob_size; specifies (chỉ định) kích thước của đối tượng dữ liệu 
        long ob_digit[1]; # bao gồm giá trị thực của integer.
    }
    ```
    
    - Minh họa lưu trữ biến integer trong C & Python
    ![Sư khác nhau C & Python integers](./figures/difference_c_python_integer.PNG)
    
        - Với C, số int là 1 nhãn cho 1 vị trí trong bộ nhớ của các bytes mã hóa 1 giá trị int.
        - Với Python, số int là 1 con trỏ tới 1 vị trí trong bộ nhớ chứa toàn bộ thông tin của object bao gồm các bytes chứa giá trị int.

## A Python List is more than just a list

+ List: định dạng có thể thay đổi nhiều thành phần

In [1]:
list_1 = list(range(10))
list_1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
print("Type of list_1: ", type(list_1))
print("Type of element in list_1: ", type(list_1[0]))

Type of list_1:  <class 'list'>
Type of element in list_1:  <class 'int'>


+ Có thể tạo list không đồng nhất (heterogeneous) kiểu dữ liệu:

In [3]:
list_2 = [True, 1, "All"]

+ Python object: bao gồm 
    - Thông tin kiểu dữ liệu 
    - Reference count (số tham chiếu)
    - Các thông tin khác (kích thước được chỉ định cho object, the actual object value)

+ Notes: 
    - list có khả năng linh động kiểu dữ liệu có thể dẫn đến dư thừa tài nguyên. 
    - list chứa 1 con trỏ chỉ tới 1 khối các con trỏ. Mỗi một con trỏ lại chỉ đến 1 đối tượng đầy đủ. 
    - Ưu điểm list là tính linh động nhưng cần cân nhắc việc cố định kiểu (dữ liệu) trong việc xử lý & lưu trữ dữ liệu.
    
+ Sự khác nhau giữa C & Python list
![difference_c_python_list](./figures/difference_c_python_list.PNG)

## Fixed-type Arrays in Python

+ Python có 1 vài lựa chọn cho việc lưu trữ dữ liệu hiêu quả, cố định kiểu dữ liệu bộ đệm.


In [4]:
import array

In [5]:
# Tạo 1 array đồng dạng
list_3 = list(range(5))
a = array.array('i', list_3)
#
a

array('i', [0, 1, 2, 3, 4])

In [6]:
import numpy as np

## Creating Arrays from Python Lists

+ **Notes**: Numpy có hạn chế là các thành phần trong 1 array phải cùng kiểu dữ liệu.

In [7]:
# int array
i_arr = np.array([1, 2, 3, 4])
i_arr

array([1, 2, 3, 4])

In [8]:
i_f_arr = np.array([3.14, 1, 2, 3])
for element in i_f_arr:
    print(type(element))
#
i_f_arr

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


array([3.14, 1.  , 2.  , 3.  ])

+ Sử dụng *dtype* để config kiểu dữ liệu cho array.

In [9]:
f_32_arr = np.array([1, 2, 3, 4], dtype='float32')
f_32_arr

array([1., 2., 3., 4.], dtype=float32)

+ Numpy array có thể tạo nhiều chiều

In [10]:
numb_dimen = 3
m_d_arr = np.array([range(i, i + numb_dimen) for i in [1, 2, 3]])
#
m_d_arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

## Create Arrays from Scratch


In [11]:
num_element = 10
zero_arr = np.zeros(num_element, dtype=int)
#
zero_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
shape_size = (3, 5)
one_arr = np.ones(shape=shape_size,
                  dtype=float)
one_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
shape_size_full = (2, 3)
full_arr = np.full(shape=shape_size_full, 
                  fill_value=3.14)
full_arr

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

+ np.arrange(start, end, step)  # theo thu tu
+ np.linspace(start, end, number_elements) # cach deu

In [14]:
arange_arr = np.arange(1, 10, 1)
arange_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
linspace_arr = np.linspace(0, 2, 10)
linspace_arr

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

+ Tao ngau nhien ma tran phan bo đồng nhất (uniformly)
```
np.random.random((shape))
```

In [16]:
uniform_arr = np.random.random(shape_size)
uniform_arr

array([[0.51431186, 0.05330872, 0.98933662, 0.77130044, 0.16556372],
       [0.25457   , 0.49365028, 0.42780601, 0.92439923, 0.58349445],
       [0.65074389, 0.37128919, 0.04141414, 0.82038049, 0.68201042]])

+ Tao ngau nhien ma tran, gia tri trong khoang [a, b] voi kich thuoc (m, n)
```
np.random.randint(a, b, (m, n))
```

In [17]:
rand_arr = np.random.randint(1, 10, (4, 5))
rand_arr

array([[8, 8, 7, 8, 7],
       [8, 4, 3, 2, 9],
       [5, 9, 4, 7, 2],
       [3, 3, 3, 7, 6]])

## Numpy Standard Data Types

![numpy_standart_data_types](./figures/numpy_standart_data_types.PNG)

# 2.2 The Basics of Numpy Arrays

+ Basic array manipulations:
    - Attributes of arrays (determining):
        - the size
        - the shape
        - the memory consumption
        - data types
    - Indexing of arrays (getting & setting):
        - the value of individual array elements.
    - Slicing of arrays (getting & setting):
        - smaller sub-arrays within a large array.
    - Reshaping of arrays
        - Changing the shape
    - Joining & splitting of arrays.   

## 2.2.1 Numpy array attributes

In [18]:
# seed with a set value in order to ensure that the same random are generated each time run code.
np.random.seed(0)
#
one_d_arr = np.random.randint(10, size=4)
#
two_d_arr = np.random.randint(10, size=(3, 4))
#
three_d_arr = np.random.randint(10, size=(2, 3, 4))
#

In [19]:
# check array 
print("3-d number of dimensions: ", three_d_arr.ndim)
print("3-d shape: ", three_d_arr.shape)
print("3-d - total size of the array", three_d_arr.size)
print("3-d - data type", three_d_arr.dtype)

3-d number of dimensions:  3
3-d shape:  (2, 3, 4)
3-d - total size of the array 24
3-d - data type int32


## 2.2.2 Array indexing: access single elements

In [20]:
print("With one-dimension, First element {} and last element {}".
                  format(one_d_arr[0], 
                         one_d_arr[-1]))

With one-dimension, First element 5 and last element 3


**Notes**
    - Không như list, numpy array là dữ liệu cố định kiểu. Nếu cố tình đưa kiểu dữ liệu khác vào, dữ liệu đó sẽ bị chuyển sang kiểu dữ liệu ban đầu (cùng dạng số) hoặc gặp lỗi.

In [21]:
# one_d_arr[0] = 'a'

## 2.2.3 Array Sclicing: Access subarrays
+ Cú pháp cắt lát numpy:
```
arr[start:end:step]
```

+ Mảng con một chiều

In [22]:
x = np.arange(10)
x_5 = x[:5]
x_5

array([0, 1, 2, 3, 4])

+ Mảng con nhiều chiều

In [23]:
m_d_arr = np.random.randint(20, size=(3, 4))
m_d_arr

array([[ 9,  0, 10,  3],
       [11, 18,  2,  0],
       [ 0,  4,  5,  6]])

In [24]:
# two rows, three columns
m_d_arr[:2, :3]

array([[ 9,  0, 10],
       [11, 18,  2]])

In [25]:
# all rows, every other column (step=2)
m_d_arr[:, ::2]

array([[ 9, 10],
       [11,  2],
       [ 0,  5]])

+ Đảo ngược array con

In [26]:
m_d_arr[::-1, ::-1]

array([[ 6,  5,  4,  0],
       [ 0,  2, 18, 11],
       [ 3, 10,  0,  9]])

+ Truy cập vào hàng và cột của array

In [27]:
# First column
print(m_d_arr[:, :1])  # subarray dimensions
print(m_d_arr[:, 0])

[[ 9]
 [11]
 [ 0]]
[ 9 11  0]


In [28]:
# first row
m_d_arr[0, :]

array([ 9,  0, 10,  3])

+ Subarray as no-copy views
    - Array slices trả về *views* thay vì copies cả một array.
    - List trong python, mỗi list slices sẽ được copies.
    - Thuộc tính này hữu ích khi ta cần làm việc với 1 vùng nhỏ trong array ban đầu mà không cần copy dữ liệu đệm bên dưới.

In [29]:
m_d_arr

array([[ 9,  0, 10,  3],
       [11, 18,  2,  0],
       [ 0,  4,  5,  6]])

In [30]:
m_d_arr_subarr = m_d_arr[:3, :2]
m_d_arr_subarr

array([[ 9,  0],
       [11, 18],
       [ 0,  4]])

In [31]:
m_d_arr_subarr[0, 0] = 10

In [32]:
m_d_arr

array([[10,  0, 10,  3],
       [11, 18,  2,  0],
       [ 0,  4,  5,  6]])

+ Creating copies of arrays
    - Copy array:
    ```
    copy()
    ```
    - Việc ta làm việc với array vừa được copy không tác động đến array ban đầu

In [33]:
m_d_arr_subarr_copy = m_d_arr[:3, :2].copy()
m_d_arr_subarr_copy

array([[10,  0],
       [11, 18],
       [ 0,  4]])

In [34]:
m_d_arr_subarr_copy[0, 0] = 11
m_d_arr_subarr_copy

array([[11,  0],
       [11, 18],
       [ 0,  4]])

In [35]:
m_d_arr

array([[10,  0, 10,  3],
       [11, 18,  2,  0],
       [ 0,  4,  5,  6]])

## 2.2.4 Reshaping of Arrays

+ Sử dụng: 
```
reshape()
```

In [36]:
grid = np.arange(1, 10).reshape(3, 3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 2.2.5 Array concatenation & Splitting
(Combine nhiều arrays thành 1 & ngược lại.)

### Concatenation (kết hợp) of arrays
```
np.concatenate([first_array, second_array, ...], axis=1)

- if axis=1: các arrays nối hàng
- if axis=0: các arrays nối cột
```

In [37]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
h = np.array([1, 2, 9])
#
z = np.concatenate([x, y, h])
z

array([1, 2, 3, 4, 5, 6, 1, 2, 9])

In [38]:
grid_1 = np.random.randint(10, size=(3, 4))
print("grid_1: \n", grid_1)
grid_2 = np.random.randint(10, size=(3, 4))
print("grid_2: \n", grid_2)
#
grid_horizontal = np.concatenate([grid_1, grid_2], axis=1)
print("Horizontal: \n", grid_horizontal)
grid_vertical = np.concatenate([grid_1, grid_2], axis=0)
print("Vertical: \n", grid_vertical)

grid_1: 
 [[8 4 1 4]
 [9 8 1 1]
 [7 9 9 3]]
grid_2: 
 [[6 7 2 0]
 [3 5 9 4]
 [4 6 4 4]]
Horizontal: 
 [[8 4 1 4 6 7 2 0]
 [9 8 1 1 3 5 9 4]
 [7 9 9 3 4 6 4 4]]
Vertical: 
 [[8 4 1 4]
 [9 8 1 1]
 [7 9 9 3]
 [6 7 2 0]
 [3 5 9 4]
 [4 6 4 4]]


+ Ngoài sử dụng axis, có thể sử dụng *np.vstack* & *np.hstack*
    - vstack: khi height size bằng nhau
    - hstack: khi weight size bằng nhau

In [39]:
x = np.array([1, 2, 3])
grid = np.array([[3, 4, 5], 
                 [5, 6, 7]])
#
horizontal_arr = np.vstack([x, grid])
horizontal_arr

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

### Splitting of arrays

+ Splitting functions:
    - np.split()
    - np.hsplit()
    - np.vsplit()

# 2.3 Computation on Numpy Arrays: Universal (phổ quát) Functions

+ Khả năng tính toán của Numpy arrays nhở sử dụng vertorized. 
    - thực thi thông qua các hàm/chức năng phổ quát - universal functions (ufuncs)

### The Slowness of Loops

In [40]:
import numpy as np
np.random.seed(0)

In [41]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output
#
values = np.random.randint(1, 10, size=5)
%timeit compute_reciprocals(values)

12.7 µs ± 292 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Introducing UFuncs

+ Compare the results:

In [42]:
print(compute_reciprocals(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [43]:
big_array = np.random.randint(1, 100, size=1000000)
#
%timeit(1.0/big_array)

UsageError: Line magic function `%timeit(1.0/big_array)` not found.


+ Các hoạt động vectorized được thực thi bởi các *ufuncs*, mục đích chính của các hàm là nhanh chóng thực hiện các hoạt động trên các giá trị của numpy array.
+ Khi cần thực hiện vòng lặp trong python, nên cân nhắc thay thế bởi vectorized.

In [44]:
np.arange(5)/np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

### Exploring NumPy's UFuncs

+ Ufuncs có 2 kiểu:
    - *unary ufuncs*: thực hiện trên 1 input.
    - *binary ufuncs*: thực hiện trên 2 inputs.
+ Ví dụ về 2 kiểu functions.    

#### Array arithmetic

In [45]:
x = np.arange(4)
#
print("x + 5 = ", x + 5)
print("x % 2 = ", x%2)

x + 5 =  [5 6 7 8]
x % 2 =  [0 1 0 1]


![array_arithmetic](./figures/array_arithmetic.PNG)

#### Absolute value

In [46]:
x = np.array([-2, -1, 1])
x_absolute = np.absolute(x)
x_absolute

array([2, 1, 1])

#### Trigonometric functions

In [47]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [48]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]


#### Exponents & logarithms

In [49]:
x = [1, 2, 3]
print("x: ", x)
print("e^x: ", np.exp(x))
print("2^x: ", np.exp2(x))
print("3^x: ", np.power(3, x))

x:  [1, 2, 3]
e^x:  [ 2.71828183  7.3890561  20.08553692]
2^x:  [2. 4. 8.]
3^x:  [ 3  9 27]


In [50]:
print("ln(x): ", np.log(x))
print("log2(x): ", np.log2(x))
print("log10(x): ", np.log10(x))

ln(x):  [0.         0.69314718 1.09861229]
log2(x):  [0.        1.        1.5849625]
log10(x):  [0.         0.30103    0.47712125]


### Advanced UFunc Features

#### Specifying output

#### Aggregates

#### Outer products

# 2.4 Aggregation: Min, Max & Everything in Between

### Summing the Values in an Array

In [51]:
list_values = np.random.random(100)
%timeit sum(list_values)

20.9 µs ± 1.41 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit np.sum(list_values)

In [ ]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

### Minimum and Maximum

In [ ]:
%timeit min(big_array)
%timeit max(big_array)

In [ ]:
%timeit np.min(big_array)
%timeit np.max(big_array)

#### Multidimensional aggregates - Tổng hợp ma trận nhiều chiều
+ Với ma trận nhiều chiều, việc tìm max/min sẽ phụ thuộc hàng hay cột
    - axis=0: tìm theo cột
    - axis=1: tìm theo hàng

In [ ]:
m_aggregates = np.random.random((3, 4))
m_aggregates

In [ ]:
np.sum(m_aggregates)


In [ ]:
m_aggregates.min(axis=0)

In [ ]:
m_aggregates.min(axis=1)

#### Other aggregation functions

![aggregation_funcs](./figures/aggregation_funcs.PNG)

### Example: What is the average height of US presidents ?

# 2.5 Computation on Arrays: Broadcasting

### Introducing Broadcasting

In [ ]:
import numpy as np

In [ ]:
a = np.array([0, 2, 3])
b = np.array([2, 3, 4])
#
a + b

+ Extend this to arrays of higher dimension
    - add a one-dimensional array to a 2-dimensional array

In [ ]:
ones_m = np.ones((3, 3))
ones_m

In [ ]:
ones_m + a

+ Involve broadcasting of both arrays

In [ ]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

In [ ]:
a

In [ ]:
b

In [ ]:
a + b

#### Visualization of Numpy broadcasting

![visualize_numpy_broadcasting](./figures/visualize_numpy_broadcasting.PNG)

### Rules of Broadcasting
+ Broadcasting tuân theo các quy tắc nhằm xác định sự tương quan giữa 2 arrays:
    - Quy tắc 1: Nếu 2 array có số chiều khác nhau, array có kích thước ít hơn có thể là bộ đệm cho array còn lại bên trái.
    - Quy tắc 2: Nếu kích thước của 2 arrays không match bất kì chiều nào, 

#### Broadcasting example 1

In [ ]:
m_ones = np.ones((2, 3))
print(m_ones.shape)
a = np.arange(3)
print(a.shape)

In [ ]:
m_ones

In [ ]:
a

In [ ]:
m_ones + a

#### Broadcasting example 2

In [ ]:
a = np.arange(3).reshape((3, 1))
print(a.shape)
b = np.arange(3)
print(b.shape)

In [ ]:
a

In [ ]:
b

In [ ]:
a + b

In [ ]:
b

### Broadcasting in Practice

#### Centering an array

In [52]:
x = np.random.random((10, 3))
x

array([[0.49555108, 0.9552979 , 0.81778172],
       [0.49902653, 0.22465879, 0.89005733],
       [0.30654364, 0.37441302, 0.75259926],
       [0.17746194, 0.10144419, 0.9999925 ],
       [0.78050216, 0.06618773, 0.6336205 ],
       [0.31063248, 0.94833285, 0.97968792],
       [0.24481674, 0.62413396, 0.75772597],
       [0.56219826, 0.49924365, 0.41224358],
       [0.54175922, 0.22209216, 0.45803492],
       [0.23090228, 0.74940011, 0.65656829]])

#### Compute the mean of each feature using the mean aggregate across 

In [55]:
x_mean_ver = x.mean(axis=0)
x_mean_ver

array([0.41493943, 0.47652044, 0.7358312 ])

In [57]:
x_mean_hor = x.mean(axis=1)
x_mean_hor

array([0.75621023, 0.53791422, 0.47785198, 0.42629954, 0.4934368 ,
       0.74621775, 0.54222555, 0.4912285 , 0.40729543, 0.54562356])

#### center the x array by subtracting the mean

In [59]:
x_centered = x - x_mean_ver
x_centered

array([[ 0.08061165,  0.47877746,  0.08195053],
       [ 0.08408709, -0.25186165,  0.15422613],
       [-0.10839579, -0.10210742,  0.01676807],
       [-0.23747749, -0.37507625,  0.2641613 ],
       [ 0.36556273, -0.4103327 , -0.1022107 ],
       [-0.10430695,  0.47181242,  0.24385672],
       [-0.1701227 ,  0.14761353,  0.02189477],
       [ 0.14725883,  0.02272321, -0.32358762],
       [ 0.12681979, -0.25442828, -0.27779628],
       [-0.18403715,  0.27287968, -0.07926291]])

#### Plotting a 2-dimensional function
+ broadcasting rất hưu dụng trong việc thể hiện ảnh 2 chiều

In [61]:
# x  & y: 50 steps from 0 -> 50
x = np.linspace(0, 5, 50)
y = np.linspace(0, 5, 50)[:, np.newaxis]

In [62]:
x

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [63]:
y

array([[0.        ],
       [0.10204082],
       [0.20408163],
       [0.30612245],
       [0.40816327],
       [0.51020408],
       [0.6122449 ],
       [0.71428571],
       [0.81632653],
       [0.91836735],
       [1.02040816],
       [1.12244898],
       [1.2244898 ],
       [1.32653061],
       [1.42857143],
       [1.53061224],
       [1.63265306],
       [1.73469388],
       [1.83673469],
       [1.93877551],
       [2.04081633],
       [2.14285714],
       [2.24489796],
       [2.34693878],
       [2.44897959],
       [2.55102041],
       [2.65306122],
       [2.75510204],
       [2.85714286],
       [2.95918367],
       [3.06122449],
       [3.16326531],
       [3.26530612],
       [3.36734694],
       [3.46938776],
       [3.57142857],
       [3.67346939],
       [3.7755102 ],
       [3.87755102],
       [3.97959184],
       [4.08163265],
       [4.18367347],
       [4.28571429],
       [4.3877551 ],
       [4.48979592],
       [4.59183673],
       [4.69387755],
       [4.795

In [65]:
z = np.sin(x)**10 + np.cos(10 + y*x)*np.cos(x)
z

array([[-0.83907153, -0.83470697, -0.8216586 , ...,  0.8956708 ,
         0.68617261,  0.41940746],
       [-0.83907153, -0.82902677, -0.8103873 , ...,  0.92522407,
         0.75321348,  0.52508175],
       [-0.83907153, -0.82325668, -0.79876457, ...,  0.96427357,
         0.84172689,  0.66446403],
       ...,
       [-0.83907153, -0.48233077, -0.01646558, ...,  0.96449925,
         0.75196531,  0.41982581],
       [-0.83907153, -0.47324558,  0.00392612, ...,  0.92542163,
         0.68540362,  0.37440839],
       [-0.83907153, -0.46410908,  0.02431613, ...,  0.89579384,
         0.65690314,  0.40107702]])

# 2.6 Comparisons, Masks & Boolean Logic

### Example: Counting Rainy Days

### Comparison operators as ufuncs

+ Có thể sử dụng phương thức so sánh thu được boolean data type.


![comparison_operators](./figures/comparison_operators.PNG)

In [67]:
x = np.array([1, 2, 3, 4, 5, 6])
x < 2

array([ True, False, False, False, False, False])

In [68]:
x > 3

array([False, False, False,  True,  True,  True])

In [69]:
x == 3

array([False, False,  True, False, False, False])

### Working with Boolean Arrays

In [72]:
x = np.random.randint(0, 9, (3, 4))
x

array([[2, 2, 1, 5],
       [1, 4, 8, 5],
       [7, 8, 6, 7]])

#### Counting entries

+ Đếm số phần tử thỏa mãn điều kiện (True) nên sử dụng hàm *np.count_nonzero()*

In [73]:
np.count_nonzero(x < 5)

5

+ Một cách khác có thể sử dụng hàm np.sum()
    - Ưu điểm: có thể sử dụng cho hàng hoặc cột

In [74]:
np.sum(x < 7, axis=0)

array([2, 2, 2, 2])

+ Ngoài ra còn có thể check:
    - Có bất kì phẩn tử nào thỏa mãn điều kiện:
    ```
    np.any(condition, axis=)
    ```
    - Tất cả các phần tử thỏa mãn điều kiện:
    ```
    np.all(condition, axis)
    ```

### Boolean operator
+ 

### Boolean Arrays as Masks

# 2.7 Fancy Indexing

### Exploring Fancy Indexing 

### Combined Indexing

### Example: Selecting random points

### Modifying values with Fancy Indexing

### Example: Binning Data

# 2.8 Sorting Arrays

### Fast Sorting in Numpy: np.sort & np.argsort

### Partial Sorts: Partitioning

### Example: k-Nearest Neighbors

# 2.9 Structured Data: NumPy's Structured Arrays

### Creating Structured Arrays

### More Advanced Compound Types

### Record Arrays: Structured Arrays with a Twist